select 
    {{ dbt.safe_cast("hvfhs_license_number", api.Column.translate_type("string")) }} hvfhs_license_number, 
    {{ dbt.safe_cast("dispatching_base_number", api.Column.translate_type("string")) }} dispatching_base_number, 
    {{ dbt.safe_cast("originating_base_number", api.Column.translate_type("string")) }} originating_base_number,
    cast(request_datetime as timestamp) request_datetime,
    cast(on_scene_datetime as timestamp) on_scene_datetime,
    cast(pickup_datetime as timestamp) pickup_datetime,
    cast(dropoff_datetime as timestamp) dropoff_datetime, 
    {{ dbt.safe_cast("pickup_location_id", api.Column.translate_type("integer")) }} pickup_location_id,
    {{ dbt.safe_cast("dropoff_location_id", api.Column.translate_type("integer")) }} dropoff_location_id,
    cast(trip_distance as float64) trip_distance, 
    {{ dbt.safe_cast("trip_time", api.Column.translate_type("integer")) }}  trip_time, 
    cast(base_passenger_fare as float64) base_passenger_fare, 
    cast(toll_amount as float64) toll_amount,
    cast(black_card_fund_amount as float64) black_card_fund_amount,
    cast(sales_tax as float64) sales_tax,
    cast(congestion_surcharge as float64) congestion_surcharge,
    cast(airport_fee as float64) airport_fee,
    cast(tip_amount as float64) tip_amount,
    cast(driver_pay_amount as float64) driver_pay_amount,
    {{ dbt.safe_cast("shared_request_flag", api.Column.translate_type("string")) }} shared_request_flag,
    {{ dbt.safe_cast("shared_match_flag", api.Column.translate_type("string")) }} shared_match_flag,
    {{ dbt.safe_cast("access_a_ride_flag", api.Column.translate_type("string")) }} access_a_ride_flag,
    {{ dbt.safe_cast("wav_request_flag", api.Column.translate_type("string")) }} wav_request_flag, 
    {{ dbt.safe_cast("wav_match_flag", api.Column.translate_type("string")) }} wav_match_flag, 
    cast(pickup_date as timestamp) pickup_date,
    {{ dbt.safe_cast("data_source", api.Column.translate_type("string")) }} data_source,
    cast(creation_dt as timestamp) creation_dt
from {{ ref('fhvhv__2_tbl_collation') }}