version: 2

sources:
  - name: clean.fhv
    description: >
      Data loaded into BigQuery using spark cluster in Dataproc. All tables in this schema represent the fist instance  
      a column_name/ordinal_position/dta_type combo was encountered. When a new combination was encountered, the data  
      was pushed to a new table. In total, there were 8 different variations of the fhv_tripdata.

    database: "{{ env_var('PROJECT_ID') }}"
    schema: "{{ env_var('BQ_RAW_SCHEMA') }}"

    tables:
      - name: fhv_tripdata_2015-01
      - name: fhv_tripdata_2017-05
      - name: fhv_tripdata_2019-03
      - name: fhv_tripdata_2019-05
      - name: fhv_tripdata_2019-07
      - name: fhv_tripdata_2020-07
      - name: fhv_tripdata_2020-08
      - name: fhv_tripdata_2023-02


models:
  - name: fhv__2_tbl_collation
    description: >
      Data loaded into BigQuery using spark cluster in Dataproc. All tables in this schema represent the fist instance  
      a column_name/ordinal_position/dta_type combo was encountered. When a new combination was encountered, the data  
      was pushed to a new table. In total, there were 8 different variations of the fhv_tripdata. 
    config:
      contract:
        enforced: true
    columns:
      - name: dispatching_base_number
        data_type: string
        description: >
          The TLC Base License Number of the base that dispatched the trip.

      - name: pickup_datetime
        data_type: timestamp
        description: >
          The date and time of the trip pick-up.

      - name: dropoff_datetime
        data_type: timestamp
        description: >
          The date and time of the trip dropoff.

      - name: pickup_location_id
        data_type: float64
        description: >
          TLC Taxi Zone in which the trip began.

      - name: dropoff_location_id
        data_type: float64
        description: >
          TLC Taxi Zone in which the trip ended.

      - name: sr_flag
        data_type: int64
        description: >
          Indicates if the trip was a part of a shared ride chain offered by a High
          Volume FHV company (e.g. Uber Pool, Lyft Line). For shared trips, the value
          is 1. For non-shared rides, this field is null.

          NOTE: For most High Volume FHV companies, only shared rides that were
          requested AND matched to another shared-ride request over the course of
          the journey are flagged. However, Lyft (base license numbers B02510 +
          B02844) also flags rides for which a shared ride was requested but another
          passenger was not successfully matched to share the trip—therefore, trips
          records with SR_Flag=1 from those two bases could indicate EITHER a first
          trip in a shared trip chain OR a trip for which a shared ride was requested but
          never matched. Users should anticipate an overcount of successfully shared
          trips completed by Lyft. 

      - name: affiliated_base_number
        data_type: string
        description: >
          Base number of the base with which the vehicle is affiliated. This
          must be provided even if the affiliated base is the same as the
          dispatching base.

      - name: pickup_date
        data_type: timestamp
        description: >
          The day truncation of `pickup_datetime`. This column was used to partition the source parquet  file after it was partially processed by the spark cluster (Dataproc).

      - name: data_source
        data_type: string
        description: >
          Bigquery bucket path where the partitioned source parquets are located.

      - name: creation_dt
        data_type: timestamp
        description: >
          Timestamp for when the data was copied over into the target schema from bigquery bucket.

      - name: clone_dt
        data_type: timestamp
        description: >
          Timestamp for when the data was cloned from the backup schema to the target raw schema. 

  - name: fhv__3_data_type
    description: >
      It safe data type casts all the columns.
    config:
      contract:
        enforced: true
    columns:
      - name: dispatching_base_number
        data_type: string
        description: >
          The TLC Base License Number of the base that dispatched the trip.

      - name: pickup_datetime
        data_type: timestamp
        description: >
          The date and time of the trip pick-up.

      - name: dropoff_datetime
        data_type: timestamp
        description: >
          The date and time of the trip dropoff.

      - name: pickup_location_id
        data_type: int64
        description: >
          TLC Taxi Zone in which the trip began.

      - name: dropoff_location_id
        data_type: int64
        description: >
          TLC Taxi Zone in which the trip ended.

      - name: sr_flag
        data_type: int64
        description: >
          Indicates if the trip was a part of a shared ride chain offered by a High
          Volume FHV company (e.g. Uber Pool, Lyft Line). For shared trips, the value
          is 1. For non-shared rides, this field is null.

          NOTE: For most High Volume FHV companies, only shared rides that were
          requested AND matched to another shared-ride request over the course of
          the journey are flagged. However, Lyft (base license numbers B02510 +
          B02844) also flags rides for which a shared ride was requested but another
          passenger was not successfully matched to share the trip—therefore, trips
          records with SR_Flag=1 from those two bases could indicate EITHER a first
          trip in a shared trip chain OR a trip for which a shared ride was requested but
          never matched. Users should anticipate an overcount of successfully shared
          trips completed by Lyft. 

      - name: affiliated_base_number
        data_type: string
        description: >
          Base number of the base with which the vehicle is affiliated. This
          must be provided even if the affiliated base is the same as the
          dispatching base.

      - name: pickup_date
        data_type: timestamp
        description: >
          The day truncation of `pickup_datetime`. This column was used to partition the source parquet  file after it was partially processed by the spark cluster (Dataproc).

      - name: data_source
        data_type: string
        description: >
          Bigquery bucket path where the partitioned source parquets are located.

      - name: creation_dt
        data_type: timestamp
        description: >
          Timestamp for when the data was copied over into the target schema from bigquery bucket.

      - name: clone_dt
        data_type: timestamp
        description: >
          Timestamp for when the data was cloned from the backup schema to the target raw schema. 

  - name: fhv__4_adds_columns
    description: >
      Adds potentially helpful columns to the fhv_tripdata set (trip_type, type start and end dates).  
      It also creates unique trip ID to establish a primary key column for further transformation steps.
      This table is materialized as it is in its final format prior to filter out records that might  
      have a negative impact on analysis. The table is partitioned by `trip_type_start_date` and is 
      clustered by: `data_source`, `pickup_date`.
    config:
      contract:
        enforced: true
    columns:
      - name: trip_type_start_date
        data_type: datetime
        description: >
          First day of the month that pickup_datetime should not be before. Table is partitioned on this column.

      - name: data_source
        data_type: string
        description: >
          Bigquery bucket path where the partitioned source parquets are located. Table is clustered on this column.

      - name: pickup_date
        data_type: timestamp
        description: >
          The day truncation of `pickup_datetime`. This column was used to partition the source parquet  file after it was partially processed by the spark cluster (Dataproc). Table is clustered on this column.

      - name: trip_type_end_date
        data_type: date
        description: >
          Last day of the month that dropoff_datetime should not be too much after (1-2 days max).

      - name: trip_type_source
        data_type: string
        description: >
          Indicates what trip data set the record was sourced from: yellow, green, fhvhv or fhv

      - name: trip_id
        data_type: string
        description: >
          unique ID created from `dbt_utils.generate_surrogate_key` by using all columns in this view.
        tests:
          - name: clean.fhv.unique_trip_id
            test_name: unique
            config:
              severity: warn

          - name: clean.fhv.null_trip_id
            test_name: not_null
            config:
              severity: warn

      - name: dispatching_base_number
        data_type: string
        description: >
          The TLC Base License Number of the base that dispatched the trip.

      - name: pickup_datetime
        data_type: timestamp
        description: >
          The date and time of the trip pick-up.

      - name: dropoff_datetime
        data_type: timestamp
        description: >
          The date and time of the trip dropoff.

      - name: pickup_location_id
        data_type: int64
        description: >
          TLC Taxi Zone in which the trip began.
        tests:
          - name: clean.fhv.eval_pickup_location
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: location_id
            severity: warn

      - name: dropoff_location_id
        data_type: int64
        description: >
          TLC Taxi Zone in which the trip ended.
        tests:
          - name: clean.fhv.eval_dropoff_location
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: location_id
            severity: warn

      - name: sr_flag
        data_type: int64
        description: >
          Indicates if the trip was a part of a shared ride chain offered by a High
          Volume FHV company (e.g. Uber Pool, Lyft Line). For shared trips, the value
          is 1. For non-shared rides, this field is null.

          NOTE: For most High Volume FHV companies, only shared rides that were
          requested AND matched to another shared-ride request over the course of
          the journey are flagged. However, Lyft (base license numbers B02510 +
          B02844) also flags rides for which a shared ride was requested but another
          passenger was not successfully matched to share the trip—therefore, trips
          records with SR_Flag=1 from those two bases could indicate EITHER a first
          trip in a shared trip chain OR a trip for which a shared ride was requested but
          never matched. Users should anticipate an overcount of successfully shared
          trips completed by Lyft. 

      - name: affiliated_base_number
        data_type: string
        description: >
          Base number of the base with which the vehicle is affiliated. This
          must be provided even if the affiliated base is the same as the
          dispatching base.

      - name: creation_dt
        data_type: timestamp
        description: >
          Timestamp for when the data was copied over into the target schema from bigquery bucket.

      - name: clone_dt
        data_type: timestamp
        description: >
          Timestamp for when the data was cloned from the backup schema to the target raw schema. 

      - name: transformation_dt
        data_type: timestamp
        description: >
          Timestamp for when the record was in the table. The principle rolw of the column to verify 
          that query cache is disabled for performance testing purposes.