name: 'pipeline_analysis_transform'
version: '1.0.0'
config-version: 2

profile: 'dbt-bq-dtc'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +incremental_strategy: "merge"
  +on_schema_change: "fail"
  pipeline_analysis_transform:

    mapping:
      +materialized: view
      +schema: mapping
      +enabled: true

    clean:
      yellow:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'trip_id'
      green:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'trip_id'
      fhvhv:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'trip_id'
      fhv:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'trip_id'

    stage:
      yellow:
        +materialized: view
        +schema: stage
        +enabled: true
      green:
        +materialized: view
        +schema: stage
        +enabled: true
      fhvhv:
        +materialized: view
        +schema: stage
        +enabled: true
      fhv:
        +materialized: view
        +schema: stage
        +enabled: true

    core1:
      +materialized: incremental
      +schema: core1
      +enabled: true
      +unique_key: 'trip_id'

    core2:
      +materialized: incremental
      +schema: core2
      +enabled: false

    mart1:
      +materialized: incremental
      +schema: mart1
      +enabled: true

    mart2:
      +materialized: incremental
      +schema: mart2
      +enabled: false

vars:
  rate_codes: [1, 2, 3, 4, 5, 6, 99]
  rate_description: ["'STANDARD RATE'", "'JFK'", "'NEWARK'", "'NASSAU/WESTCHESTER'", "'NEGOTIATED FARE'", "'GROUP RIDE'", "'UNKNOWN'"]
  payment_types: [1, 2, 3, 4, 5, 6]
  payment_description: ["'FLEX FARE TRIP'", "'CREDIT CARD'", "'CASH'", "'NO CHARGE'", "'DISPUTE'", "'UNKNOWN'", "'VOIDED TRIP'"]
  run_tag: 'core1/mart1 - full refresh - (6) - datasource'

on-run-end:
  - "{{ get_query_history() }}"
