name: 'pipeline_analysis_transform'
version: '1.0.0'
config-version: 2

profile: 'dbt-bq-dtc'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  pipeline_analysis_transform:

    mapping:
      +materialized: view
      +schema: mapping
      +enabled: true

    clean:
      yellow:
        +materialized: view
        +schema: clean
        +enabled: true
      green:
        +materialized: view
        +schema: clean
        +enabled: true
      fhvhv:
        +materialized: view
        +schema: clean
        +enabled: true

    stage:
      yellow:
        +materialized: view
        +schema: stage
        +enabled: true
      green:
        +materialized: view
        +schema: stage
        +enabled: true
      fhvhv:
        +materialized: view
        +schema: stage
        +enabled: true

    core1:
      yellow:
        +materialized: table
        +schema: core1
        +enabled: true