name: 'pipeline_analysis_transform'
version: '1.0.0'
config-version: 2

profile: 'dbt-bq-dtc'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  +incremental_strategy: "merge"
  +on_schema_change: "fail"
  pipeline_analysis_transform:

    mapping:
      +materialized: view
      +schema: mapping
      +enabled: true

    clean:
      yellow:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'data_source'
      green:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'data_source'
      fhvhv:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'data_source'
      fhv:
        +materialized: view
        +schema: clean
        +enabled: true
        +unique_key: 'data_source'

    stage:
      yellow:
        +materialized: view
        +schema: stage
        +enabled: true
        +unique_key: 'data_source'
      green:
        +materialized: view
        +schema: stage
        +enabled: true
        +unique_key: 'data_source'
      fhvhv:
        +materialized: view
        +schema: stage
        +enabled: true
        +unique_key: 'data_source'
      fhv:
        +materialized: view
        +schema: stage
        +enabled: true
        +unique_key: 'data_source'

    core1:
      +materialized: incremental
      +schema: core1
      +enabled: true

vars:
  rate_codes: [1, 2, 3, 4, 5, 6, 99]
  payment_types: [1, 2, 3, 4, 5, 6]
  run_tag: 'abc123'

on-run-end: 
  - "{{ get_query_history() }}"