version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/pipeline-analysis-446021-e6b585f9b41d.json"
  GOOGLE_LOCATION: EU # Optional
dev: 
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/pipeline-analysis-446021-e6b585f9b41d.json"
  GOOGLE_LOCATION: EU # Optional