version: 2

models:
  - name: mart1_dm_daily_revenue
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""
        tests:
          - name: mart1.daily.eval_pickup_name
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: pickup_service_zone
        data_type: string
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""
        tests:
          - name: mart1.daily.eval_dropoff_name
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_service_zone
        data_type: string
        description: ""

      - name: pickup_date
        data_type: timestamp
        description: ""

      - name: pickup_public_holiday
        data_type: boolean
        description: ""

      - name: ratecode_description
        data_type: string
        description: ""

      - name: payment_description
        data_type: string
        description: ""

      - name: trip_type
        data_type: string
        description: ""

      - name: hvfs_description
        data_type: string
        description: ""

      - name: avg_trip_distance
        data_type: float64
        description: ""

      - name: avg_trip_duration_min
        data_type: float64
        description: ""

      - name: fare_amount
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: total_amount
        data_type: float64
        description: ""

      - name: total_fees
        data_type: float64
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: num_trips
        data_type: int64
        description: ""

      - name: transformation_dt
        data_type: timestamp
        description: ""

  - name: mart1_dm_monthly_revenue
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""
        tests:
          - name: mart1.monthly.eval_pickup_name
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: pickup_service_zone
        data_type: string
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""
        tests:
          - name: mart1.monthly.eval_dropoff_name
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_service_zone
        data_type: string
        description: ""

      - name: pickup_month
        data_type: timestamp
        description: ""

      - name: ratecode_description
        data_type: string
        description: ""

      - name: payment_description
        data_type: string
        description: ""

      - name: trip_type
        data_type: string
        description: ""

      - name: hvfs_description
        data_type: string
        description: ""

      - name: avg_trip_distance
        data_type: float64
        description: ""

      - name: avg_trip_duration_min
        data_type: float64
        description: ""

      - name: fare_amount
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: total_amount
        data_type: float64
        description: ""

      - name: total_fees
        data_type: float64
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: num_trips
        data_type: int64
        description: ""

      - name: num_public_holidays
        data_type: int64
        description: ""
        tests:
          - name: mart1.monthly.eval_num_public_holidays
            test_name: dbt_utils.accepted_range
            min_value: 0
            max_value: 31
            inclusive: true

      - name: transformation_dt
        data_type: timestamp
        description: ""