version: 2 

models:
  - name: core1_yellow_fact_trips
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: trip_type_start_date
        data_type: timestamp
        description: ""

      - name: data_source
        data_type: string
        description: ""

      - name: trip_type_source
        data_type: string
        description: ""

      - name: pickup_date
        data_type: timestamp
        description: ""

      - name: trip_id
        data_type: string
        description: ""
        tests:
          - name: core1.yellow.unique_trip_id
            test_name: unique
            config:
              severity: warn

          - name: core1.yellow.null_trip_id
            test_name: not_null
            config:
              severity: warn

      - name: vendor_id
        data_type: int64
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: trip_type_end_date
        data_type: timestamp
        description: ""

      - name: trip_duration_min
        data_type: int64
        description: ""

      - name: pickup_year
        data_type: int64
        description: ""

      - name: pickup_weekday_num
        data_type: int64
        description: ""

      - name: pickup_weekday_name
        data_type: string
        description: ""

      - name: pickup_month
        data_type: int64
        description: ""

      - name: pickup_hour
        data_type: int64
        description: ""

      - name: pickup_public_holiday
        data_type: boolean
        description: ""

      - name: pickup_rush_hour_status
        data_type: string
        description: ""

      - name: dropoff_year
        data_type: int64
        description: ""

      - name: dropoff_weekday_num
        data_type: int64
        description: ""

      - name: dropoff_weekday_name
        data_type: string
        description: ""

      - name: dropoff_month
        data_type: int64
        description: ""

      - name: dropoff_hour
        data_type: int64
        description: ""

      - name: dropoff_public_holiday
        data_type: boolean
        description: ""

      - name: dropoff_rush_hour_status
        data_type: string
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""
        tests:
          - name: core1.yellow.eval_pickup_name
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: pickup_service_zone
        data_type: string
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""
        tests:
          - name: core1.yellow.eval_dropoff_name
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_service_zone
        data_type: string
        description: ""

      - name: ratecode_description
        data_type: string
        description: ""
        tests:
          - name: core1.yellow.eval_rate_description
            test_name: accepted_values
            values: "{{ var('rate_description') }}"  
            severity: warn 
            quote: false

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: payment_description
        data_type: string
        description: ""
        tests: 
          - name: core1.yellow.eval_payment_description
            test_name: accepted_values
            values: "{{ var('payment_description') }}"
            severity: warn 
            quote: false

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: float64
        description: ""

      - name: fare_amount
        data_type: float64
        description: ""

      - name: extra_amount
        data_type: float64
        description: ""

      - name: mta_tax
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: tolls_amount
        data_type: float64
        description: ""

      - name: improvement_surcharge
        data_type: float64
        description: ""

      - name: total_amount
        data_type: float64
        description: ""

      - name: congestion_surcharge
        data_type: float64
        description: ""

      - name: airport_fee
        data_type: float64
        description: ""

      - name: clone_dt
        data_type: timestamp
        description: ""

      - name: transformation_dt
        data_type: timestamp
        description: ""

  - name: core1_green_fact_trips
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: trip_type_start_date
        data_type: timestamp
        description: ""

      - name: data_source
        data_type: string
        description: ""

      - name: trip_type_source
        data_type: string
        description: ""

      - name: pickup_date
        data_type: timestamp
        description: ""

      - name: trip_id
        data_type: string
        description: ""
        tests:
          - name: core1.green.unique_trip_id
            test_name: unique
            config:
              severity: warn
          - name: core1.green.null_trip_id
            test_name: not_null
            config:
              severity: warn

      - name: vendor_id
        data_type: int64
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: trip_type_end_date
        data_type: timestamp
        description: ""

      - name: trip_duration_min
        data_type: int64
        description: ""

      - name: pickup_year
        data_type: int64
        description: ""

      - name: pickup_weekday_num
        data_type: int64
        description: ""

      - name: pickup_weekday_name
        data_type: string
        description: ""

      - name: pickup_month
        data_type: int64
        description: ""

      - name: pickup_hour
        data_type: int64
        description: ""

      - name: pickup_public_holiday
        data_type: boolean
        description: ""

      - name: pickup_rush_hour_status
        data_type: string
        description: ""

      - name: dropoff_year
        data_type: int64
        description: ""

      - name: dropoff_weekday_num
        data_type: int64
        description: ""

      - name: dropoff_weekday_name
        data_type: string
        description: ""

      - name: dropoff_month
        data_type: int64
        description: ""

      - name: dropoff_hour
        data_type: int64
        description: ""

      - name: dropoff_public_holiday
        data_type: boolean
        description: ""

      - name: dropoff_rush_hour_status
        data_type: string
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""
        tests:
          - name: core1.green.eval_pickup_name
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: pickup_service_zone
        data_type: string
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""
        tests:
          - name: core1.green.eval_dropoff_name
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_service_zone
        data_type: string
        description: ""

      - name: ratecode_description
        data_type: string
        description: ""
        tests:
          - name: core1.green.eval_rate_description
            test_name: accepted_values
            values: "{{ var('rate_description') }}"
            severity: warn 
            quote: false

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: payment_description
        data_type: string
        description: ""
        tests:
          - name: core1.green.eval_payment_description
            test_name: accepted_values
            values: "{{ var('payment_description') }}"
            severity: warn 
            quote: false

      - name: trip_type
        data_type: int64
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: float64
        description: ""

      - name: fare_amount
        data_type: float64
        description: ""

      - name: extra_amount
        data_type: float64
        description: ""

      - name: mta_tax
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: tolls_amount
        data_type: float64
        description: ""

      - name: ehail_fee
        data_type: float64
        description: ""

      - name: improvement_surcharge
        data_type: float64
        description: ""

      - name: total_amount
        data_type: float64
        description: ""

      - name: congestion_surcharge
        data_type: float64
        description: ""

      - name: clone_dt
        data_type: timestamp
        description: ""

      - name: transformation_dt
        data_type: timestamp
        description: ""

  - name: core1_fhvhv_fact_trips
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: trip_type_start_date
        data_type: timestamp
        description: ""

      - name: data_source
        data_type: string
        description: ""

      - name: trip_type_source
        data_type: string
        description: ""

      - name: pickup_date
        data_type: timestamp
        description: ""

      - name: trip_id
        data_type: string
        description: ""
        tests:
          - name: core1.fhvhv.unique_trip_id
            test_name: unique
            config:
              severity: warn
          - name: core1.fhvhv.null_trip_id
            test_name: not_null
            config:
              severity: warn

      - name: hvfhs_license_number
        data_type: string
        description: ""

      - name: hvfs_description
        data_type: string
        description: ""

      - name: dispatching_base_number
        data_type: string
        description: ""

      - name: originating_base_number
        data_type: string
        description: ""

      - name: request_datetime
        data_type: timestamp
        description: ""

      - name: on_scene_datetime
        data_type: timestamp
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: trip_type_end_date
        data_type: timestamp
        description: ""

      - name: trip_time
        data_type: int64
        description: ""

      - name: trip_duration_min
        data_type: int64
        description: ""

      - name: pickup_year
        data_type: int64
        description: ""

      - name: pickup_weekday_num
        data_type: int64
        description: ""

      - name: pickup_weekday_name
        data_type: string
        description: ""

      - name: pickup_month
        data_type: int64
        description: ""

      - name: pickup_hour
        data_type: int64
        description: ""

      - name: pickup_public_holiday
        data_type: boolean
        description: ""

      - name: pickup_rush_hour_status
        data_type: string
        description: ""

      - name: dropoff_year
        data_type: int64
        description: ""

      - name: dropoff_weekday_num
        data_type: int64
        description: ""

      - name: dropoff_weekday_name
        data_type: string
        description: ""

      - name: dropoff_month
        data_type: int64
        description: ""

      - name: dropoff_hour
        data_type: int64
        description: ""

      - name: dropoff_public_holiday
        data_type: boolean
        description: ""

      - name: dropoff_rush_hour_status
        data_type: string
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: pickup_service_zone
        data_type: string
        description: ""
        tests:
          - name: core1.fhvhv.eval_pickup_name
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""
        tests:
          - name: core1.fhvhv.eval_dropoff_name
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_service_zone
        data_type: string
        description: ""

      - name: trip_distance
        data_type: float64
        description: ""

      - name: shared_request_flag
        data_type: string
        description: ""

      - name: shared_match_flag
        data_type: string
        description: ""

      - name: access_a_ride_flag
        data_type: string
        description: ""

      - name: wav_request_flag
        data_type: string
        description: ""

      - name: wav_match_flag
        data_type: string
        description: ""

      - name: base_passenger_fare
        data_type: float64
        description: ""

      - name: toll_amount
        data_type: float64
        description: ""

      - name: black_card_fund_amount
        data_type: float64
        description: ""

      - name: sales_tax
        data_type: float64
        description: ""

      - name: congestion_surcharge
        data_type: float64
        description: ""

      - name: airport_fee
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: driver_pay_amount
        data_type: float64
        description: ""

      - name: clone_dt
        data_type: timestamp
        description: ""

      - name: transformation_dt
        data_type: timestamp
        description: ""

  - name: core1_fhv_fact_trips
    description: ""
    config:
      contract:
        enforced: true
    columns:
      - name: trip_type_start_date
        data_type: timestamp
        description: ""

      - name: data_source
        data_type: string
        description: ""

      - name: trip_type_source
        data_type: string
        description: ""

      - name: pickup_date
        data_type: timestamp
        description: ""

      - name: trip_id
        data_type: string
        description: ""
        tests:
          - name: core1.fhv.unique_trip_id
            test_name: unique
            config:
              severity: warn

          - name: core1.fhv.null_trip_id
            test_name: not_null
            config:
              severity: warn

      - name: dispatching_base_number
        data_type: string
        description: ""

      - name: affiliated_base_number
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: trip_type_end_date
        data_type: timestamp
        description: ""

      - name: trip_duration_min
        data_type: int64
        description: ""

      - name: pickup_year
        data_type: int64
        description: ""

      - name: pickup_weekday_num
        data_type: int64
        description: ""

      - name: pickup_weekday_name
        data_type: string
        description: ""

      - name: pickup_month
        data_type: int64
        description: ""

      - name: pickup_hour
        data_type: int64
        description: ""

      - name: pickup_public_holiday
        data_type: boolean
        description: ""

      - name: pickup_rush_hour_status
        data_type: string
        description: ""

      - name: dropoff_year
        data_type: int64
        description: ""

      - name: dropoff_weekday_num
        data_type: int64
        description: ""

      - name: dropoff_weekday_name
        data_type: string
        description: ""

      - name: dropoff_month
        data_type: int64
        description: ""

      - name: dropoff_hour
        data_type: int64
        description: ""

      - name: dropoff_public_holiday
        data_type: boolean
        description: ""

      - name: dropoff_rush_hour_status
        data_type: string
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""
        tests:
          - name: core1.fhv.eval_pickup_name
            test_name: relationships
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: pickup_service_zone
        data_type: string
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""
        tests:
          - name: core1.fhv.eval_dropoff_name
            test_name: relationships 
            to: source('mapping.map', 'taxi_zone_lookup')
            field: zone
            severity: warn

      - name: dropoff_service_zone
        data_type: string
        description: ""

      - name: sr_flag
        data_type: int64
        description: ""

      - name: app_company_affiliation
        data_type: string
        description: ""

      - name: clone_dt
        data_type: timestamp
        description: ""

      - name: transformation_dt
        data_type: timestamp
        description: ""