select 
    {{ update_vendor_id("vendor_id") }} vendor_id,
    cast(pickup_datetime as timestamp) pickup_datetime,
    cast(dropoff_datetime as timestamp) dropoff_datetime,
    {{ update_store_and_fwd_flag("store_and_fwd_flag") }}  store_and_fwd_flag,
    {{ update_ratecode_id("ratecode_id", "pickup_location_id", "dropoff_location_id") }} ratecode_id,
    {{ dbt.safe_cast("pickup_location_id", api.Column.translate_type("integer")) }} pickup_location_id,
    {{ dbt.safe_cast("dropoff_location_id", api.Column.translate_type("integer")) }} dropoff_location_id,
    {{ dbt.safe_cast("passenger_count", api.Column.translate_type("integer")) }} passenger_count,
    cast(trip_distance as float64) trip_distance,
    cast(fare_amount as float64) fare_amount,
    cast(null as float64) extra_amount,
    cast(mta_tax as float64) mta_tax,
    cast(tip_amount as float64) tip_amount,
    cast(tolls_amount as float64) tolls_amount,
    cast(ehail_fee as float64) ehail_fee,
    cast(null as float64) improvement_surcharge,
    cast(total_amount as float64) total_amount,
    {{ update_payment_type("payment_type", "tip_amount") }} payment_type,
    {{ dbt.safe_cast("trip_type", api.Column.translate_type("integer")) }} trip_type,
    cast(congestion_surcharge as float64) congestion_surcharge,
    cast(pickup_date as timestamp) pickup_date,
    {{ dbt.safe_cast("data_source", api.Column.translate_type("string")) }} data_source,
    cast(creation_dt as timestamp) creation_dt
from {{ ref('green__2_tbl_collation') }}